/* Factory Chile® beta: interfaz premium en HTML5, CSS3 y JavaScript ES6 sin frameworks. */
const brandLogos = {
  factory: `<svg viewBox="0 0 520 180" aria-label="Factory Chile logo" role="img"><defs><linearGradient id="gold" x1="0" x2="1"><stop stop-color="#fff"/><stop offset=".42" stop-color="#D4AF37"/><stop offset="1" stop-color="#E91E63"/></linearGradient></defs><rect x="18" y="18" width="144" height="144" rx="38" fill="#0B0B0B" stroke="#D4AF37"/><path d="M55 54h82v22H80v20h45v21H80v39H55z" fill="url(#gold)"/><circle cx="408" cy="72" r="4" fill="#D4AF37"/><text x="190" y="82" fill="url(#gold)" font-size="44" font-weight="800" letter-spacing="5">FACTORY</text><text x="190" y="124" fill="#fff" font-size="30" letter-spacing="12">CHILE®</text></svg>`,
  perfume: `<svg viewBox="0 0 240 240" aria-label="Perfume Factory logo"><circle cx="120" cy="120" r="104" fill="#0B0B0B" stroke="#D4AF37" stroke-width="7"/><path d="M92 56h56v26H92z" fill="#D4AF37"/><path d="M84 86h72l18 32v44c0 18-15 33-33 33H99c-18 0-33-15-33-33v-44z" fill="#0B0B0B" stroke="#D4AF37" stroke-width="7"/><path d="M91 135h58l-12 28h-34z" fill="#E91E63" opacity=".85"/><circle cx="183" cy="76" r="13" fill="#E91E63"/><path d="M74 174h92" stroke="#E91E63" stroke-width="6" stroke-linecap="round"/><text x="120" y="214" text-anchor="middle" fill="#fff" font-size="17" letter-spacing="4">PERFUME</text></svg>`,
  beauty: `<svg viewBox="0 0 240 240" aria-label="Beauty Factory logo"><circle cx="120" cy="120" r="104" fill="#0B0B0B" stroke="#D4AF37" stroke-width="7"/><path d="M86 84h34v77c0 9-7 16-16 16h-2c-9 0-16-7-16-16z" fill="#0B0B0B" stroke="#D4AF37" stroke-width="7"/><path d="M89 84c4-22 14-36 31-45v45z" fill="#E91E63"/><path d="M128 166l36-76" stroke="#D4AF37" stroke-width="9" stroke-linecap="round"/><path d="M153 90c16-10 34-4 42 12-15 9-32 13-49 7z" fill="#E91E63"/><path d="M58 160h52M132 160h50" stroke="#E91E63" stroke-width="6" stroke-linecap="round"/><text x="120" y="214" text-anchor="middle" fill="#fff" font-size="17" letter-spacing="5">BEAUTY</text></svg>`,
  fashion: `<svg viewBox="0 0 240 240" aria-label="Fashion Factory logo"><circle cx="120" cy="120" r="104" fill="#0B0B0B" stroke="#D4AF37" stroke-width="7"/><path d="M120 48c0-16 26-16 26 2 0 16-26 17-26 40" fill="none" stroke="#D4AF37" stroke-width="8" stroke-linecap="round"/><path d="M120 90L46 148c-12 9-5 27 10 27h128c15 0 22-18 10-27z" fill="none" stroke="#D4AF37" stroke-width="8"/><path d="M72 158h96" stroke="#E91E63" stroke-width="7" stroke-linecap="round"/><text x="120" y="145" text-anchor="middle" fill="#D4AF37" font-size="42" font-weight="800">FF</text><text x="120" y="197" text-anchor="middle" fill="#fff" font-size="18" letter-spacing="5">FASHION</text></svg>`
};

const products = ['Golden Aura','Noir Signature','Rose Intelligence','Velvet Serum','Diamond Glow','Atelier Brush','Black Essential','Santiago Silk','Executive Hoodie','Aura Mist','Factory Ritual','Urban Leather'].map((name, i) => ({ name, price: [89900,74900,64900,45900,52900,29900,39900,69900,59900,34900,48900,79900][i], type: ['perfume','perfume','perfume','beauty','beauty','beauty','fashion','fashion','fashion','perfume','beauty','fashion'][i] }));
const icons = ['Calidad Premium','Innovación','Diseño Exclusivo','Compra Segura','Despachos','Atención Personalizada'];
const blog = ['El nuevo lujo latinoamericano nace desde Chile','Cómo elegir una fragancia que represente tu historia','Beauty Factory y la precisión de una rutina inteligente','Fashion Factory: básicos elevados para una presencia ejecutiva','Factory Lab: personalización, IA y memoria olfativa','Factory Club: fidelización transversal en un solo ecosistema'];

function logoBlock(key, small=false){ return `<div class="logo-mark ${small?'small':''}">${brandLogos[key]}</div>`; }
function money(n){ return new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(n); }

function render(){
  document.querySelector('#app').innerHTML = `
  <nav class="nav" aria-label="Navegación principal"><a class="nav-brand" href="#inicio">${logoBlock('factory',true)}</a><button class="menu" aria-label="Abrir menú">☰</button><div class="nav-links">${['Inicio','Perfume Factory','Beauty Factory','Fashion Factory','Factory Lab','Factory Club','Tienda','Seguimiento','Blog','Contacto'].map(t=>`<a href="#${t.toLowerCase().replaceAll(' ','-')}">${t}</a>`).join('')}</div></nav>
  <section id="inicio" class="hero section"><div class="orb one"></div><div class="hero-copy reveal">${logoBlock('factory')}<span class="eyebrow">Una marca, tres esencias.</span><h1>FACTORY CHILE®</h1><p>Un ecosistema de lujo contemporáneo donde fragancia, belleza y moda convergen con tecnología, membresías inteligentes y una experiencia lista para evolucionar a e-commerce premium.</p><div class="actions"><a class="btn gold" href="#tienda">Comprar</a><a class="btn ghost" href="#quienes-somos">Conocer más</a></div></div><aside class="hero-console reveal"><b>Beta corporativa oficial</b><span>Arquitectura preparada para Login · Registro · Admin · Inventario · API REST · Mercado Pago · WebPay · Carrito · Backend.</span><div class="metric"><strong>3</strong><small>divisiones premium</small></div><div class="metric"><strong>∞</strong><small>fórmulas registrables</small></div></aside></section>
  <section class="division-grid section">${division('perfume','Perfume Factory','Fragancias de autor, códigos olfativos memorables y rituales personales diseñados para dejar presencia.', 'Ver catálogo')}${division('beauty','Beauty Factory','Belleza elegante y tecnológica: cuidado, color, brochas y rutinas con lenguaje de alta cosmética.', 'Explorar belleza')}${division('fashion','Fashion Factory','Moda, accesorios y prendas con siluetas modernas, materiales nobles y actitud ejecutiva contemporánea.', 'Ver colección')}</section>
  <section id="quienes-somos" class="section about reveal"><div>${logoBlock('factory',true)}<span class="eyebrow">Quiénes somos</span><h2>Una casa chilena diseñada para competir visualmente en el mercado global.</h2><p>Factory Chile® nace para construir un ecosistema de consumo premium: productos propios, experiencia omnicanal, fidelización transversal y personalización asistida por IA.</p></div><div class="timeline">${['Historia: creación de una marca paraguas con tres divisiones coherentes.','Misión: elevar la experiencia diaria mediante diseño, aroma y belleza inteligente.','Visión: convertirnos en una plataforma latinoamericana de lifestyle premium.','Valores: precisión, confianza, innovación, elegancia y servicio humano.'].map((x,i)=>`<article><b>0${i+1}</b><p>${x}</p></article>`).join('')}</div></section>
  <section class="section"><span class="eyebrow">Por qué elegirnos</span><h2>Lujo funcional con infraestructura escalable.</h2><div class="cards six">${icons.map((x,i)=>`<article class="card reveal"><svg viewBox="0 0 64 64"><circle cx="32" cy="32" r="24"/><path d="M20 34l8 8 18-22"/></svg><h3>${x}</h3><p>${['Selección cuidada y presentación de alto estándar.','Factory IA y procesos preparados para datos.','Familia visual propia, sobria y reconocible.','Flujos pensados para pagos y trazabilidad.','Operación proyectada para despachos nacionales.','Contacto directo, asistencia y postventa premium.'][i]}</p></article>`).join('')}</div></section>
  <section id="factory-lab" class="section lab reveal"><div>${logoBlock('factory',true)}<span class="eyebrow">Factory Lab</span><h2>Perfumes personalizados con memoria de fórmula.</h2><p>Factory Lab permitirá crear esencias completamente personalizadas: el cliente responde un test inteligente, Factory IA analiza su personalidad y se genera una fragancia exclusiva registrada para recompra exacta mediante código personal.</p><ol>${['Responder un test inteligente.','Factory IA analiza la personalidad.','Se genera una fragancia exclusiva.','La fórmula queda registrada para siempre.','Recompra exacta con código personal.'].map(x=>`<li>${x}</li>`).join('')}</ol><a class="btn gold" href="#contacto">Crear mi esencia</a></div><div class="formula-card"><small>Cliente</small><b>María González</b><small>Código</small><b>FC-000145</b><small>Fragancia</small><b>Golden Aura</b><span>Fórmula registrada</span></div></section>
  <section id="factory-club" class="section club">${logoBlock('factory',true)}<span class="eyebrow">Factory Club</span><h2>Un programa de fidelización para todo el ecosistema.</h2><p>Los clientes acumulan Factory Points en Perfume Factory, Beauty Factory y Fashion Factory. No importa dónde compren: todo pertenece a Factory Chile®.</p><div class="tiers">${['Silver|Acceso anticipado, puntos base y regalos estacionales.','Gold|Multiplicador de puntos, envíos preferentes y eventos privados.','Black Signature|Concierge, fórmulas prioritarias y beneficios de máxima exclusividad.'].map(t=>{const [a,b]=t.split('|');return `<article class="tier"><h3>${a}</h3><p>${b}</p><strong>Factory Points</strong></article>`}).join('')}</div></section>
  <section id="tienda" class="section"><span class="eyebrow">Tienda beta</span><h2>Productos destacados listos para catálogo.</h2><div class="products">${products.map(product).join('')}</div></section>
  <section id="seguimiento" class="section tracking reveal"><span class="eyebrow">Seguimiento</span><h2>Trazabilidad visual del pedido.</h2><div>${['Pedido recibido','Preparando','Despachado','En camino','Entregado'].map((x,i)=>`<article style="--i:${i}"><b>${i+1}</b><span>${x}</span></article>`).join('')}</div></section>
  <section id="blog" class="section"><span class="eyebrow">Blog</span><h2>Contenido editorial para posicionamiento premium.</h2><div class="cards">${blog.map((x,i)=>`<article class="card editorial"><small>Factory Journal 0${i+1}</small><h3>${x}</h3><p>Una mirada estratégica al diseño, tecnología, consumo premium y nuevas experiencias de marca.</p></article>`).join('')}</div></section>
  <section id="contacto" class="section contact"><div>${logoBlock('factory',true)}<span class="eyebrow">Contacto</span><h2>Hablemos de crecimiento, distribución y experiencia de marca.</h2><p><b>Karmen Fermin</b><br>Gerente General · +54 9 11 3302 8424</p><p><b>Jorge A. Parra Harrys</b><br>Director Comercial · +56 9 2946 7522</p><p><b>ventas@factory.cl</b></p><div class="map">Santiago · Chile<br><small>Mapa corporativo referencial</small></div></div><form><input placeholder="Nombre"><input placeholder="Correo"><input placeholder="Teléfono"><input placeholder="Empresa"><textarea placeholder="Mensaje"></textarea><button class="btn gold" type="button">Enviar mensaje</button></form></section>
  <footer class="footer">${logoBlock('factory',true)}<div>${['Perfume Factory','Beauty Factory','Fashion Factory','Factory Lab','Factory Club','WhatsApp','Instagram','Facebook','TikTok','LinkedIn'].map(x=>`<a href="#">${x}</a>`).join('')}</div><p>Factory Chile® · Todos los derechos reservados © ${new Date().getFullYear()}</p></footer>
  <button class="ai-fab" aria-label="Abrir Factory IA">Factory IA</button><aside class="ai-panel"><button class="ai-close">×</button><b>Hola. Soy Factory IA.</b><p>Estoy aquí para ayudarte.</p><p>¿Cómo puedo asistirte hoy?</p><div class="chat"><span>Quiero crear una fragancia personalizada.</span><span>Perfecto. Podemos iniciar tu test inteligente y proyectar una fórmula exclusiva.</span></div></aside>`;
  bind();
}
function division(key,title,txt,btn){return `<article id="${title.toLowerCase().replaceAll(' ','-')}" class="division reveal">${logoBlock(key,true)}<h2>${title}</h2><p>${txt}</p><a class="btn ghost" href="#tienda">${btn}</a></article>`}
function product(p){return `<article class="product reveal"><div class="product-art ${p.type}">${brandLogos[p.type]}</div><h3>${p.name}</h3><p>${money(p.price)}</p><span aria-label="5 estrellas">★★★★★</span><button>Agregar al carrito</button></article>`}
function bind(){
  const nav=document.querySelector('.nav'), links=document.querySelector('.nav-links'); window.addEventListener('scroll',()=>nav.classList.toggle('scrolled',scrollY>24)); document.querySelector('.menu').onclick=()=>links.classList.toggle('open');
  const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('in')), {threshold:.12}); document.querySelectorAll('.reveal,.card,.product').forEach(el=>io.observe(el));
  document.querySelector('.ai-fab').onclick=()=>document.querySelector('.ai-panel').classList.add('open'); document.querySelector('.ai-close').onclick=()=>document.querySelector('.ai-panel').classList.remove('open');
  const cursor=document.querySelector('.cursor'); addEventListener('pointermove',e=>{cursor.style.translate=`${e.clientX}px ${e.clientY}px`;}); initParticles(); setTimeout(()=>document.querySelector('.loader').classList.add('done'),900);
}
function initParticles(){const c=document.querySelector('#particles'),x=c.getContext('2d');let w,h,pts=[];function size(){w=c.width=innerWidth;h=c.height=innerHeight;pts=Array.from({length:70},()=>({x:Math.random()*w,y:Math.random()*h,r:Math.random()*2+.4,s:Math.random()*.35+.1}))}function draw(){x.clearRect(0,0,w,h);x.fillStyle='rgba(212,175,55,.55)';pts.forEach(p=>{p.y-=p.s;if(p.y<0)p.y=h;x.beginPath();x.arc(p.x,p.y,p.r,0,7);x.fill()});requestAnimationFrame(draw)}addEventListener('resize',size);size();draw()}
render();
